/** v1 AdvancedSearchDialog / PostRequest skill suggestions (Bible-aligned category strip names). */
export const SKILLS_BY_CATEGORY: Record<string, string[]> = {
  "Health + Wellness": [
    "Yoga",
    "Fitness",
    "Nutrition",
    "Mental Health",
    "Meditation",
    "Personal Training",
    "Weight Loss",
  ],
  "Home Improvement": [
    "Plumbing",
    "Electrical",
    "Carpentry",
    "Painting",
    "HVAC",
    "Landscaping",
    "Remodeling",
  ],
  Culinary: [
    "Cooking",
    "Baking",
    "Recipe Development",
    "Food Safety",
    "Meal Planning",
    "Nutrition",
    "Vegan Cooking",
  ],
  "Technical Support": [
    "Computer Repair",
    "Software Installation",
    "Network Troubleshooting",
    "Data Recovery",
    "Windows",
    "Mac",
  ],
  Tutoring: ["Math", "Science", "English", "SAT Prep", "ACT Prep", "Homework Help", "Study Skills"],
  Beauty: ["Makeup", "Skincare", "Hair Styling", "Nail Art", "Beauty Products", "Color Theory"],
  "Arts, Music, Design": [
    "Guitar",
    "Piano",
    "Singing",
    "Photography",
    "Graphic Design",
    "Drawing",
    "Music Theory",
  ],
  "App + Web Development": [
    "React",
    "Node.js",
    "Python",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Full-Stack",
  ],
  "Business + Marketing": [
    "Marketing",
    "SEO",
    "Social Media",
    "Business Strategy",
    "Content Marketing",
    "Analytics",
  ],
  Everyday: [
    "Life Skills",
    "Organization",
    "Time Management",
    "Productivity",
    "Cleaning",
    "Cooking Basics",
  ],
  Other: [],
};
